MM-2712: Added slices for .appointmentType
Nictiz/Nictiz-STU3-eAfspraak pull request #8
Opened 2022-02-18 14:39 UTC by NictizEduard

2022-02-18 17:04 UTC, jduwel requested changes
Los van de individuele comments:

1. Hoe je het wendt of keert is dit geen patch. Hoe zien jullie dit voor je?
2. Binnen een CodeableConcept 2 .codings meegeven mag alleen als er slechts wat verschil in granulariteit is tussen verschillende codesystems (zie core spec). Als ik in het ticket lees dat de bedoeling is om in de ene .coding 'OTH' mee te sturen en dan in de andere 'telefonisch consult', dan _mag dat gewoon niet_. Hebben jullie hier over nagedacht?

2022-02-18 17:04 UTC, jd-nictiz commented on Profiles/eAfspraak-Appointment.xml
> +          <display value= "ContactTypeCodelijst"/>
Incorrecte spatie

2022-02-18 17:04 UTC, jd-nictiz commented on Profiles/eAfspraak-Appointment.xml
> +    <element id="Appointment.appointmentType:ContactTypeCodelijst">
Ik zie op deze slice niet terug dat deze minimaal 1 keer moet voorkomen zoals jullie in het ticket aangeven

2022-02-18 17:04 UTC, jd-nictiz commented on Profiles/eAfspraak-Appointment.xml
> +      </slicing>
Je kunt je vraagtekens zetten bij een slicing op coding.system, terwijl de binding van ContactTypeCodelijst 'extensible' is. Over het algemeen werken dit soort slicings alleen bij 'required' bindings lijkt me.

2022-02-18 17:04 UTC, jd-nictiz commented on Profiles/eAfspraak-Appointment.xml
> +      </slicing>
Ook: de slicing moet op coding, niet op appointmentType. appointmentType heeft cardinaliteit 0..1 dus mag helemaal niet twee keer voorkomen

2022-02-18 17:04 UTC, jduwel commented on Profiles/eAfspraak-Appointment.xml
> +        <strength value="extensible"/>
Idem opmerking over extensible binding

2022-02-21 09:05 UTC, NictizEduard commented
@niekvangalen  Kan jij de wijziging controleren? Omdat Jorn afwezig is.

2022-02-21 10:36 UTC, niekvangalen requested changes
Graag verplaatsen naar patchrelease maart.

2022-03-09 10:00 UTC, closed without merging